version: '3.2'

services:
    hadoop:
        build:
            context: .
            dockerfile: ./Docker/Dockerfile
        ports:
            # Hdfs ports
            - "50010:50010"
            - "50020:50020"
            - "50070:50070"
            - "50075:50075"
            - "50090:50090"
            # mapred ports
            - "19888:19888"
            # yarn ports
            - "8030:8030"
            - "8031:8031"
            - "8032:8032"
            - "8033:8033"
            - "8040:8040"
            - "8042:8042"
            - "8088:8088"
            # others
            - "49707:49707"
            - "2122:2122"
            # spark
            - "8080:8080"
            - "7077:7077"
        command: tail -f /dev/null
        volumes:
            - "./share:/usr/local/share"
            - "./mongodbData:/data/db"
        
